-- MySQL Script generated by MySQL Workbench
-- Tue May 16 14:23:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema devoir3db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema devoir3db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devoir3db` DEFAULT CHARACTER SET utf8 ;
USE `devoir3db` ;

-- -----------------------------------------------------
-- Table `devoir3db`.`devoir3_db`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adventures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heading` VARCHAR(200) NULL,
  `tripdate` DATE NULL,
  `duration` INT NULL,
  `summary` TEXT(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;